// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftqytzbshinbglgacrtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0cXl0emJzaGluYmdsZ2FjcnRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5Njg4MDksImV4cCI6MjA2MDU0NDgwOX0.W5WLVBVDPt33w2EZt0XUzYVY5KUoDJ44VOqoze6huHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);